export const Constants = {
  PLAYER_HEIGHT: 1.6,
  PLAYER_WALK_SPEED: 5,
  PLAYER_SPRINT_SPEED: 8,
  PLAYER_JUMP_SPEED: 5,
  MOUSE_SENSITIVITY: 0.002,
  MAX_HUNGER: 100,
  MAX_THIRST: 100,
  MAX_HEALTH: 100,
  HUNGER_DECAY_RATE: 0.1, // per second
  THIRST_DECAY_RATE: 0.15,
  HEALTH_REGEN_RATE: 0.05,
  DAY_LENGTH_SECONDS: 300 // 5 minutes per day
} as const;
